/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { PrintfulClient } from './PrintfulClient';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AdditionalPlacements } from './models/AdditionalPlacements';
export type { Address } from './models/Address';
export type { ApprovalSheetWebhookFile } from './models/ApprovalSheetWebhookFile';
export type { AvailabilityStatus } from './models/AvailabilityStatus';
export type { BaseMockupProduct } from './models/BaseMockupProduct';
export { CalculationStatus } from './models/CalculationStatus';
export { CatalogItem } from './models/CatalogItem';
export { CatalogItemSummary } from './models/CatalogItemSummary';
export type { CatalogMockupProduct } from './models/CatalogMockupProduct';
export type { CatalogOption } from './models/CatalogOption';
export { CatalogShippingRateItem } from './models/CatalogShippingRateItem';
export type { CatalogStockUpdatedEventConfigurationRequest } from './models/CatalogStockUpdatedEventConfigurationRequest';
export type { Category } from './models/Category';
export type { CategoryId } from './models/CategoryId';
export type { ColorsFilter } from './models/ColorsFilter';
export type { Costs } from './models/Costs';
export type { Country } from './models/Country';
export type { Currency } from './models/Currency';
export { CustomBorderColorOption } from './models/CustomBorderColorOption';
export type { Customization } from './models/Customization';
export type { DefaultEventConfigurationRequest } from './models/DefaultEventConfigurationRequest';
export type { DesignPlacement } from './models/DesignPlacement';
export { dPuffOption } from './models/dPuffOption';
export type { Error } from './models/Error';
export type { EventConfigurationRequest } from './models/EventConfigurationRequest';
export type { EventConfigurationResponse } from './models/EventConfigurationResponse';
export type { EventType } from './models/EventType';
export type { FileLayer } from './models/FileLayer';
export type { FileOptionPrices } from './models/FileOptionPrices';
export type { FilterSettings } from './models/FilterSettings';
export type { Gift } from './models/Gift';
export type { HateoasLink } from './models/HateoasLink';
export type { HateoasLink_2 } from './models/HateoasLink_2';
export type { HeaderSource } from './models/HeaderSource';
export { InsideLabelTypeOption } from './models/InsideLabelTypeOption';
export { InsidePocketOption } from './models/InsidePocketOption';
export type { Item } from './models/Item';
export type { ItemExternalId } from './models/ItemExternalId';
export type { ItemId } from './models/ItemId';
export type { ItemWithoutPlacements } from './models/ItemWithoutPlacements';
export type { Layer } from './models/Layer';
export type { LayerOptionPrices } from './models/LayerOptionPrices';
export type { LayerOptions } from './models/LayerOptions';
export type { LayerPosition } from './models/LayerPosition';
export type { Layers } from './models/Layers';
export { LifelikeOption } from './models/LifelikeOption';
export type { Limit } from './models/Limit';
export type { Limit_2 } from './models/Limit_2';
export type { Locale } from './models/Locale';
export type { Measurement } from './models/Measurement';
export type { MeasurementUnit } from './models/MeasurementUnit';
export type { MeasurementValue } from './models/MeasurementValue';
export type { Mockup } from './models/Mockup';
export type { MockupGeneratorIds } from './models/MockupGeneratorIds';
export { MockupGeneratorTask } from './models/MockupGeneratorTask';
export type { MockupPlacementsFilter } from './models/MockupPlacementsFilter';
export type { MockupStyleIds } from './models/MockupStyleIds';
export type { MockupStyles } from './models/MockupStyles';
export { MockupTaskCreation } from './models/MockupTaskCreation';
export { MockupTemplates } from './models/MockupTemplates';
export type { NewFilter } from './models/NewFilter';
export { NotesOption } from './models/NotesOption';
export { OAuthScope } from './models/OAuthScope';
export type { Offset } from './models/Offset';
export type { Offset_2 } from './models/Offset_2';
export type { Order } from './models/Order';
export type { OrderId } from './models/OrderId';
export type { OrderSummary } from './models/OrderSummary';
export type { PackingSlip } from './models/PackingSlip';
export type { Paging } from './models/Paging';
export type { ParameterSource } from './models/ParameterSource';
export { Placement } from './models/Placement';
export type { Placement as PlacementType } from './models/Placement';
export type { PlacementOptions } from './models/PlacementOptions';
export type { PlacementsFilter } from './models/PlacementsFilter';
export type { PlacementsList } from './models/PlacementsList';
export type { PointerSource } from './models/PointerSource';
export type { ProblemDetails } from './models/ProblemDetails';
export type { Product } from './models/Product';
export type { ProductCategoryIds } from './models/ProductCategoryIds';
export type { ProductData } from './models/ProductData';
export type { ProductId } from './models/ProductId';
export type { ProductInfo } from './models/ProductInfo';
export type { ProductLinks } from './models/ProductLinks';
export type { ProductOptions } from './models/ProductOptions';
export type { ProductPrices } from './models/ProductPrices';
export type { ProductSizeGuide } from './models/ProductSizeGuide';
export type { ProductsLinks } from './models/ProductsLinks';
export type { ProductsParam } from './models/ProductsParam';
export type { Response200 } from './models/Response200';
export type { RetailCosts } from './models/RetailCosts';
export { SellingRegion } from './models/SellingRegion';
export { SellingRegionAll } from './models/SellingRegionAll';
export type { SellingRegionPrice } from './models/SellingRegionPrice';
export { SellingRegionStockAvailability } from './models/SellingRegionStockAvailability';
export type { ServerErrorDetails } from './models/ServerErrorDetails';
export { Shipment } from './models/Shipment';
export type { ShipmentItem } from './models/ShipmentItem';
export type { ShippingRatesAddress } from './models/ShippingRatesAddress';
export type { ShowExpired } from './models/ShowExpired';
export { SizeTable } from './models/SizeTable';
export { SortDirection } from './models/SortDirection';
export { SortType } from './models/SortType';
export { StitchColorOption } from './models/StitchColorOption';
export type { StoreId } from './models/StoreId';
export { TechniqueEnum } from './models/TechniqueEnum';
export type { Techniques } from './models/Techniques';
export type { TechniquesFilter } from './models/TechniquesFilter';
export type { TechniqueStockAvailability } from './models/TechniqueStockAvailability';
export type { TemplateMockupProduct } from './models/TemplateMockupProduct';
export { ThreadColorsOption } from './models/ThreadColorsOption';
export type { TrackingEvent } from './models/TrackingEvent';
export type { Type } from './models/Type';
export { UnlimitedColorOption } from './models/UnlimitedColorOption';
export type { Variant } from './models/Variant';
export type { VariantColor } from './models/VariantColor';
export type { VariantId } from './models/VariantId';
export type { VariantImage } from './models/VariantImage';
export type { VariantImages } from './models/VariantImages';
export type { VariantPrices } from './models/VariantPrices';
export type { VariantsPriceData } from './models/VariantsPriceData';
export type { VariantStockAvailability } from './models/VariantStockAvailability';
export type { VariantTechniquePrice } from './models/VariantTechniquePrice';
export { WarehouseItem } from './models/WarehouseItem';
export { WarehouseItemSummary } from './models/WarehouseItemSummary';
export { WarehouseShippingRateItem } from './models/WarehouseShippingRateItem';
export type { Webhook } from './models/Webhook';
export type { WebhookCreated } from './models/WebhookCreated';
export type { WebhookInfoRequest } from './models/WebhookInfoRequest';
export type { WebhookInfoResponse } from './models/WebhookInfoResponse';
export type { WebhookOrderData } from './models/WebhookOrderData';
export type { WebhookShipmentData } from './models/WebhookShipmentData';

export { CatalogV2Service } from './services/CatalogV2Service';
export { CountriesV2Service } from './services/CountriesV2Service';
export { MockupGeneratorV2Service } from './services/MockupGeneratorV2Service';
export { OAuthScopesV2Service } from './services/OAuthScopesV2Service';
export { OrdersV2Service } from './services/OrdersV2Service';
export { ShippingRatesV2Service } from './services/ShippingRatesV2Service';
export { WebhookV2Service } from './services/WebhookV2Service';
